version: '3.8'

services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    ports:
      - '8000:8000'
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ecommerce_mysql
      DB_USERNAME: ecommerce_mysql_user
      DB_PASSWORD: j3gNKOKX9IMLFzOIXvwpT9gfOlkaPhIM
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ecommerce_mysql
      POSTGRES_USER: ecommerce_mysql_user
      POSTGRES_PASSWORD: j3gNKOKX9IMLFzOIXvwpT9gfOlkaPhIM
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres-data:
